# Copyright (c) 2026, Mahaveer and contributors
# License: MIT
"""Notifications for the Mahaveer app: an in-app inbox, and Web Push to the phone.

Every notification is FIRST a row in `MM App Notification` (the bell), and only then a
push. The row is the record: a phone that is off, a browser that refused permission, a
server without `pywebpush` — none of them lose the message, they only lose the buzz.

Push is standard Web Push (VAPID). The key pair is generated by the app the first time
anyone turns notifications on and kept in MM Settings, so there is nothing to configure.
Sending runs in a background job after the triggering transaction commits, so a slow or
dead push service never holds up an approval or a challan.

iPhones only receive Web Push from an app that was added to the Home Screen (iOS 16.4+);
the screen says so when it asks for permission.
"""

import base64
import hashlib
import json

import frappe
from frappe import _
from frappe.utils import cint, get_url, now_datetime

APP_BASE = "/mahaveermetalic"


# --------------------------------------------------------------------------- keys

def _push_libs():
	try:
		import py_vapid  # noqa: F401
		import pywebpush  # noqa: F401

		return True
	except ImportError:
		return False


def _b64url(raw: bytes) -> str:
	return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def _vapid_keys(create=True):
	"""(public, private) as base64url strings; generated once, on first need."""
	from frappe.utils.password import get_decrypted_password, set_encrypted_password

	public = frappe.db.get_single_value("MM Settings", "vapid_public_key")
	private = get_decrypted_password("MM Settings", "MM Settings", "vapid_private_key", raise_exception=False)
	if public and private:
		return public.strip(), private.strip()
	if not create or not _push_libs():
		return None, None

	# Two first subscribers at once must not mint two key pairs — whichever subscription
	# was made under the losing pair would never receive anything.
	frappe.db.sql("select get_lock('mm_vapid_keys', 10)")
	try:
		public = frappe.db.get_single_value("MM Settings", "vapid_public_key")
		private = get_decrypted_password("MM Settings", "MM Settings", "vapid_private_key", raise_exception=False)
		if public and private:
			return public.strip(), private.strip()

		from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
		from py_vapid import Vapid01

		v = Vapid01()
		v.generate_keys()
		private = _b64url(v.private_key.private_numbers().private_value.to_bytes(32, "big"))
		public = _b64url(v.public_key.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint))
		# No commit here: this runs inside a POST (push_config) or the migrate patch, and both
		# commit on their own. Committing mid-request would also commit whatever else the
		# caller had written so far.
		frappe.db.set_single_value("MM Settings", "vapid_public_key", public)
		set_encrypted_password("MM Settings", "MM Settings", private, "vapid_private_key")
		return public, private
	finally:
		frappe.db.sql("select release_lock('mm_vapid_keys')")


# --------------------------------------------------------------------------- device side

def ensure_keys():
	"""Mint the push key pair if the server can push and has none yet (migrate patch)."""
	return _vapid_keys(create=True)


@frappe.whitelist(methods=["POST"])
def push_config():
	"""What the app needs to subscribe this device. POST because the first call may have
	to mint the key pair, and only a POST is committed by Frappe at the end."""
	if not _push_libs():
		return {"enabled": False, "reason": _("Phone notifications are not set up on the server yet.")}
	public, _private = _vapid_keys()
	return {"enabled": bool(public), "public_key": public}


@frappe.whitelist(methods=["POST"])
def subscribe(subscription, user_agent=None):
	"""Remember this device for the logged-in user. Idempotent per endpoint.

	A device that was subscribed under another login (a shared office phone) is moved to
	this user: the browser holds one subscription per app, so it can only ever reach the
	person currently signed in on it.
	"""
	if frappe.session.user == "Guest":
		frappe.throw(_("Please sign in first."), frappe.PermissionError)
	sub = json.loads(subscription) if isinstance(subscription, str) else (subscription or {})
	endpoint = (sub.get("endpoint") or "").strip()
	keys = sub.get("keys") or {}
	if not endpoint.startswith("https://") or not keys.get("p256dh") or not keys.get("auth"):
		frappe.throw(_("This browser sent an incomplete push subscription."))
	digest = hashlib.sha256(endpoint.encode()).hexdigest()
	existing = frappe.db.get_value("MM Push Subscription", {"endpoint_hash": digest}, "name")
	values = {
		"user": frappe.session.user,
		"endpoint": endpoint,
		"p256dh": keys["p256dh"],
		"auth": keys["auth"],
		"user_agent": (user_agent or "")[:500],
		"failures": 0,
	}
	if existing:
		frappe.db.set_value("MM Push Subscription", existing, values)
		return {"ok": True, "name": existing}
	doc = frappe.get_doc({"doctype": "MM Push Subscription", "endpoint_hash": digest, **values})
	doc.insert(ignore_permissions=True)
	return {"ok": True, "name": doc.name}


@frappe.whitelist(methods=["POST"])
def unsubscribe(endpoint):
	digest = hashlib.sha256((endpoint or "").strip().encode()).hexdigest()
	name = frappe.db.get_value(
		"MM Push Subscription", {"endpoint_hash": digest, "user": frappe.session.user}, "name"
	)
	if name:
		frappe.delete_doc("MM Push Subscription", name, ignore_permissions=True, force=True)
	return {"ok": True}


@frappe.whitelist()
def inbox(limit=40):
	"""This user's notifications, newest first, with the unread count."""
	user = frappe.session.user
	if user == "Guest":
		return {"rows": [], "unread": 0}
	rows = frappe.get_all(
		"MM App Notification",
		filters={"user": user},
		fields=["name", "title", "body", "url", "category", "read", "creation"],
		order_by="creation desc",
		limit_page_length=min(max(cint(limit) or 40, 1), 200),
	)
	unread = frappe.db.count("MM App Notification", {"user": user, "read": 0})
	return {"rows": rows, "unread": unread}


@frappe.whitelist(methods=["POST"])
def mark_read(name=None):
	"""One notification, or (no name) all of them."""
	filters = {"user": frappe.session.user, "read": 0}
	if name:
		filters["name"] = name
	for n in frappe.get_all("MM App Notification", filters=filters, pluck="name"):
		frappe.db.set_value("MM App Notification", n, "read", 1, update_modified=False)
	return {"ok": True}


@frappe.whitelist(methods=["POST"])
def send_test():
	"""A test buzz to every device of the person pressing the button."""
	notify(
		[frappe.session.user],
		_("Notifications are on"),
		_("You will get order updates on this device."),
		url=APP_BASE,
		category="test",
		now=True,
	)
	devices = frappe.db.count("MM Push Subscription", {"user": frappe.session.user})
	return {"devices": devices}


@frappe.whitelist(allow_guest=True, methods=["GET"])
def service_worker():
	"""The service worker script, served from here so it can control /mahaveermetalic.

	A worker only controls pages under its own URL's folder unless the response says
	otherwise. The built file lives under /assets/..., which could never control the app,
	so it is read off disk and served with `Service-Worker-Allowed`.
	"""
	from werkzeug.wrappers import Response

	path = frappe.get_app_path("mahaveermetalic", "public", "mahaveermetalic", "sw.js")
	try:
		with open(path, encoding="utf-8") as f:
			body = f.read()
	except OSError:
		body = "/* service worker not built */"
	resp = Response(body, mimetype="application/javascript")
	# No trailing slash: the app's own start URL is "/mahaveermetalic", and a scope of
	# "/mahaveermetalic/" would leave that very page uncontrolled.
	resp.headers["Service-Worker-Allowed"] = APP_BASE
	resp.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
	return resp


# --------------------------------------------------------------------------- sending

def notify(users, title, body=None, url=None, category=None, reference=None, now=False):
	"""Record a notification for each user and push it to their devices.

	Never raises: a notification is a side-effect of something that already happened
	(an approval, an urgent flag), and failing to tell someone must not undo it.
	`reference` = (doctype, name).
	"""
	try:
		users = sorted({u for u in (users or []) if u and u not in ("Guest",)})
		if not users:
			return []
		names = []
		for user in users:
			doc = frappe.get_doc({
				"doctype": "MM App Notification",
				"user": user,
				"title": (title or "")[:140],
				"body": body or "",
				"url": url or APP_BASE,
				"category": category or "",
				"reference_doctype": reference[0] if reference else None,
				"reference_name": reference[1] if reference else None,
			})
			doc.insert(ignore_permissions=True)
			names.append(doc.name)
			frappe.publish_realtime(
				"mm_notification", {"title": doc.title, "body": doc.body, "url": doc.url},
				user=user, after_commit=True,
			)
		if now or frappe.flags.in_test:
			deliver_push(names)
		else:
			frappe.enqueue(
				"mahaveermetalic.mahaveer_metallic.api.push.deliver_push",
				queue="short",
				notification_names=names,
				enqueue_after_commit=True,
			)
		return names
	except Exception:
		frappe.log_error(title="Mahaveer notify failed", message=frappe.get_traceback())
		return []


def deliver_push(notification_names):
	"""Background: send each notification to every device of its user."""
	if not _push_libs():
		return
	public, private = _vapid_keys(create=False)
	if not private:
		return
	from pywebpush import WebPushException, webpush

	claims_sub = get_url()
	if not claims_sub.startswith("https://"):
		# Push services want a contact; an http dev URL is not one. mailto: always is.
		claims_sub = "mailto:admin@mahaveermetalic.com"

	for name in notification_names or []:
		n = frappe.db.get_value(
			"MM App Notification", name, ["user", "title", "body", "url", "category"], as_dict=True
		)
		if not n:
			continue
		payload = json.dumps({
			"title": n.title,
			"body": n.body or "",
			"url": n.url or APP_BASE,
			"tag": n.category or "mm",
			"urgent": n.category in ("urgent", "approval"),
		})
		reached = 0
		for sub in frappe.get_all(
			"MM Push Subscription",
			filters={"user": n.user},
			fields=["name", "endpoint", "p256dh", "auth", "failures"],
		):
			try:
				webpush(
					subscription_info={"endpoint": sub.endpoint, "keys": {"p256dh": sub.p256dh, "auth": sub.auth}},
					data=payload,
					vapid_private_key=private,
					vapid_claims={"sub": claims_sub},
					ttl=24 * 3600,
					headers={"Urgency": "high" if n.category in ("urgent", "approval") else "normal"},
					timeout=10,
				)
				reached += 1
				frappe.db.set_value(
					"MM Push Subscription", sub.name,
					{"last_success": now_datetime(), "failures": 0}, update_modified=False,
				)
			except WebPushException as e:
				status = getattr(getattr(e, "response", None), "status_code", None)
				if status in (404, 410):
					# The browser dropped this subscription (app uninstalled, permission
					# revoked). It will never work again.
					frappe.delete_doc("MM Push Subscription", sub.name, ignore_permissions=True, force=True)
				else:
					_count_failure(sub)
			except Exception:
				_count_failure(sub)
		frappe.db.set_value("MM App Notification", name, "pushed", reached, update_modified=False)


def _count_failure(sub):
	failures = cint(sub.failures) + 1
	if failures >= 10:
		frappe.delete_doc("MM Push Subscription", sub.name, ignore_permissions=True, force=True)
	else:
		frappe.db.set_value("MM Push Subscription", sub.name, "failures", failures, update_modified=False)


def purge_old_notifications():
	"""Daily: read notifications older than 60 days go; unread ones stay until read."""
	frappe.db.sql(
		"""delete from `tabMM App Notification`
		where `read` = 1 and creation < date_sub(now(), interval 60 day)"""
	)
